AWSTemplateFormatVersion: 2010-09-09
Description: Creates an AutoScaling Group with Port 22 open

Parameters:
  KeyName:
    Type: String
    Description: Name of the Keypair you wish to use for your EC2 Instance

Resources:
  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-10918173
      InstanceType: t2.nano
      KeyName: !Ref KeyName
      SecurityGroups: 
          - !Ref InstanceSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sdm
          Ebs:
            VolumeType: gp2
            VolumeSize: 10

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH inbound rule security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: !GetAZs ''
      LaunchConfigurationName: !Ref LaunchConfiguration
      MaxSize: '1'
      MinSize: '1'
      Tags:
        - Key: Name
          Value: AutoScale Stack Test
          PropagateAtLaunch: true
